version: 0.2

phases:
  install:
    commands:
      - echo "Install Stage..."
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 730335570050.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t optimusv2app .
      - docker tag optimusv2app:latest 730335570050.dkr.ecr.ap-southeast-1.amazonaws.com/optimus_ecr_uat:latest
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - docker push 730335570050.dkr.ecr.ap-southeast-1.amazonaws.com/optimus_ecr_uat:latest
      - echo "Creating imagedefinitions.json file..."
      # - "echo '[{\"name\":\"dotnetapplication\",\"imageUri\":\"621695400690.dkr.ecr.ap-southeast-1.amazonaws.com/dotnetapplication:latest\"}]' | Out-File -FilePath imagedefinitions.json -Encoding utf8"
      - printf '[{"name":"app","imageUri":"730335570050.dkr.ecr.ap-southeast-1.amazonaws.com/optimus_ecr_uat:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  name: "BuildArtif"%                      
